name:  Dispatch event - deploy nucleus on dev

on:
  push:
    branches:
      - "dev"
      - "main"

jobs:
  trigger_dispatch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Extract repository info and trigger custom dispatch
      run: |
        # Extract the repository name and branch from the payload
        REPO_NAME=${{ github.repository }}
        BRANCH_NAME=${{ github.ref }}
        SHA=${{ github.sha }}

        # Clean the branch name (remove "refs/heads/" part)
        BRANCH_NAME=${BRANCH_NAME#refs/heads/}

        # Display the repository and branch information
        echo "Repository: $REPO_NAME"
        echo "Branch: $BRANCH_NAME"
        echo "SHA: $SHA"

        # Trigger the dispatch event to the target repository
        curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPOSITORY_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/zime-ai/zime-deploy/dispatches \
            -d '{"event_type": "deploy-nucleus-dev", "client_payload": {"branch": "'"$BRANCH_NAME"'", "repository": "'"$REPO_NAME"'", "sha": "'"$GITHUB_SHA"'"}}'
